'use strict';
// tests for createCar
// Generated by serverless-mocha-plugin

const mod         = require('../createCar/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const assert      = mochaPlugin.chai.assert;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-createCar'
}

describe('createCar', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda 
    wrapper.init(mod);

    done()
  })
  
  it('Should create a car', (done) => {
    wrapper.run({
      make: 'Test Car',
      year: 2020,
      mileage: 999
    }, (err, response) => {

      assert.isNotOk(err);
      assert.isOk(response);
      assert.isOk(response.id);
      assert.isAbove(response.id.length, 16);
      assert.equal(response.make, 'Test Car');
      assert.equal(response.year, 2020);
      assert.equal(response.mileage, 999);

      done();
    });
  });



  it('Should require a make', (done) => {
    wrapper.run({
      year: 2020,
      mileage: 999
    }, (err, response) => {

      assert.isOk(err);
      assert.isNotOk(response);
      
      done();
    });
  });
});
